Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping_Hexora.Services;
using Shopping_Hexora.ViewModels;

namespace Shopping_Hexora.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IItemService _itemService;
        private readonly IRatingService _ratingService;
        private readonly IUserService _userService;
        private readonly IManageItemService _manageItemService;

        public ItemsController(ICategoryService categoryService, IItemService itemService, 
            IRatingService ratingService, IUserService userService, IManageItemService manageItemService)
        {
            _categoryService = categoryService;
            _itemService = itemService;
            _ratingService = ratingService;
            _userService = userService;
            _manageItemService = manageItemService;
        }
        [Authorize]
        public IActionResult Index()
        {
            var items = _itemService.GetItemsByUserId(); 
            return View(items);
        }
        public IActionResult Details(int itemId)
        {
            var item =_itemService.GetById(itemId);
            if (item is null) return NotFound();

            var usertRate = _ratingService.GetUserRate(_userService.GetUserId(), itemId);
            ViewBag.userRate = usertRate;
            var productRate = _ratingService.GetProductRate(itemId);
            ViewBag.productRate = productRate;

            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _manageItemService.GetAllCategories();

            var vm = new CreateItemVM
            {
                Categories = categories.Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList() // .ToList() eklemeyi unutma
            };

            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateItemVM model , Stock stock)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _itemService.Create(model,stock);
            return RedirectToAction ("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            // 1- get item by id 
            var item = _itemService.GetById(id);
            if (item is null) return NotFound();
            // 3- create vm object
            EditItemVM model = new()
            {
                Id = id,
                Name = item.Name,
                Description = item.Description,
                CategoryId = item.CategoryId,
                Price = item.Price,
                Categories = _categoryService.GetSelectList(),
                CurrentCover = item.Cover,
                Quantity = item.Stock.Quantity
                 

            };
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditItemVM model )
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var item =await _itemService.Update(model);
            //if (item is null) return BadRequest();
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _itemService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }

        public IActionResult RateProduct(string ratingValue, int itemId)
        {
            var isRated = _ratingService.RateProduct(Int32.Parse(ratingValue), itemId, _userService.GetUserId());
            if (isRated < 0)
            {
                return BadRequest();
            }
            return Ok();
        }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shopping_Hexora.Constants;

namespace Shopping_Hexora.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        private readonly UserManager<IdentityUser> _user;
        private readonly RoleManager<IdentityRole> _roles;
        public RolesController(UserManager<IdentityUser> user, RoleManager<IdentityRole> roles)
        {
            _user = user;
            _roles = roles;
        }
        public async Task<IActionResult> Index()
        {
            var _users = await _user.Users.ToListAsync();
            return View(_users);
        }
        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _user.FindByIdAsync(userId);
            var userRoles = await _user.GetRolesAsync(user);

            var allRoles = await _roles.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new roleViewModel()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _user.FindByIdAsync(userId);

            List<roleViewModel> myRoles =
                JsonConvert.DeserializeObject<List<roleViewModel>>(jsonRoles);

            if (user != null)
            {
                var userRoles = await _user.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _user.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _user.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Controllers/StockController.cs
namespace Shopping_Hexora.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly IStockService _stockService;
        public StockController(IStockService stockService )
        {
            _stockService = stockService;
        }
        public async Task <IActionResult> Index()
        {
            var itemStock = await _stockService.GetStocks();
            return View(itemStock);
        }
        [HttpGet]
        public async Task<IActionResult> ManangeStock(int itemId)
        {
            var stock = await _stockService.GetStockByItemId(itemId);

            var dtoStock = new StockDTO
            {
                ItemId = itemId,
                Quantity = stock != null ? stock.Quantity : 0,
            };
            return View(dtoStock);
        }
        [HttpPost]
        public async Task<IActionResult> ManangeStock(StockDTO model)
        {
            if (!ModelState.IsValid)
                return View(model);
            try
            {
                await _stockService.ManageStock(model);
                TempData["successMessage"] = "Stock is updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!!";
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/UserOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shopping_Hexora.Models;
using Shopping_Hexora.Services;

namespace Shopping_Hexora.Controllers
{
    [Authorize]
    public class UserOrderController : Controller
    {
        private readonly IUserOrderService _userOrderService;
        public UserOrderController(IUserOrderService userOrderService)
        {
            _userOrderService = userOrderService;
        }
        public async Task<IActionResult> UserOrders()
        {
            var orders = await _userOrderService.UserOrders();
            return View(orders);
        }
         
        public async Task<IActionResult> GetDetail(int orderId)
        {
            var detail =await _userOrderService.GetOrderDetail(orderId);
            return View(detail);
        }
        
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
     
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    @* BootStrap *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <!--DtataTable-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.bootstrap5.css" />

    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/Shopping_Hexora.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/adminstyle.css" />
     
</head>
<body>
    <div class="main-container"> 
            
            @* side nav bar *@
        <nav class="sidenav list-group ">

            <a class="navigation-link   " asp-controller="Home" asp-action="Index">Back To Home</a>
            <a class="navigation-link   " asp-controller="AdminOperations" asp-action="Dashboard">    Dashboard  </a>
            <a class="navigation-link   " asp-controller="Roles" asp-action="Index">User Roles</a> 
            <a class="navigation-link   " asp-area="" asp-controller="AdminOperations" asp-action="GetAllItems">Manage Products  </a>
            <a class="navigation-link   " asp-controller="AdminOperations" asp-action="AllOrders">Orders</a>
            <a class="navigation-link   " asp-controller="Stock" asp-action="Index">Stock</a> 
            <a href="/Reports/TopFiveSellingBooks" class="navigation-link  "><i class="bi bi-bar-chart"></i> Top Salling Items</a> 
            
                </nav>
             @*  upper nav bar *@
        <div class="right-panel">
            <nav class="nav-bar">
                <div class="nav-heading">Welcome @User.Identity?.Name</div>
                <div class="nav-actions">
                    <a href="/Identity/Account/Manage/Index" class="navigation-link"><i class="bi bi-gear"></i> Manage account</a>
                    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit" class="navigation-link">
                            <i class="bi bi-box-arrow-left"></i> Logout
                        </button>
                    </form>
                </div>
            </nav>
            <div class="content container">
                @RenderBody()
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <!-- Bootstrap core JS-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--DtataTable-->
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js "></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js "></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping_Hexora</title> 
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> 
     @* BootStrap *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <!--DtataTable-->  
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.bootstrap5.css" />
    
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" /> 
     
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shopping_Hexora.styles.css" asp-append-version="true" />

</head>
<body class="bg-light">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand  " style="width:75px" asp-controller="Home" asp-action="Index">
                <img src="~/assets/img/navbar2.svg" alt="..." />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Products">Products</a></li> 
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Seller DashBord
                        </a>
                        <ul class="dropdown-menu">
                            
                            <li><a class="dropdown-item" asp-controller="Items" asp-action="Index">My Products</a></li>
                            <li><a class="dropdown-item" asp-controller="Stock" asp-action="Index">Manage Stock</a></li> 
                             
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="UserOrder" asp-action="UserOrders">Track Order </a>
                    </li> 
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    @if (User.IsInRole(Shopping_Hexora.Constants.Roles.Admin.ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="AdminOperations" asp-action="Dashboard">Admin Dashboard</a>
                        </li>
                    }
                    @* <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li> *@ 
                </ul> 
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav> 
    <div  >
        <div class="my-0">
            <partial name="_Notifications" />
        </div>  
        <main role="main" class="pb-3">
           
            @RenderBody()
    
        </main>
    
   </div>

    <!-- Footer-->
    <footer class="footer border-top   py-4"  >
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Tüm Hakları Saklıdır &copy; Hexora System 2026</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" asp-controller="Home" asp-action="Privacy">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS--> 
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> 
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--DtataTable--> 
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js "></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js "></script>
    
    <!--Cart counter-->
    <script>
        loadCartCount();
        async function loadCartCount() {
            try {
                var response = await fetch(`/Cart/GetTotalItemInCart`);
                console.log(response)
                if (response.status == 200) {
                    var result = await response.json();
                    var cartCountEl = document.getElementById("cartCount");
                    cartCountEl.innerHTML = result;
                }
            }
            catch (err) {
                console.log(err);
            }
        }
    </script>

     


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notifications.cshtml
 

@* this from bootstrap alert*@

 ﻿@if (TempData["successMessage"] is not null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["successMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["errorMessage"] is not null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["errorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}